server:
  enabled: true
  config: |
    storage "consul" {
      address = "consul-server:8500"
      path    = "vault/"
    }
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
    ui = true

ui:
  enabled: true

injector:
  enabled: true

affinity: {}
nodeSelector: {}
tolerations: []
resources: {}
