apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-hub.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "notification-hub.name" . }}
    helm.sh/chart: {{ include "notification-hub.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8089 }}
      targetPort: {{ .Values.service.port | default 8089 }}
  selector:
    app.kubernetes.io/name: {{ include "notification-hub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
