name: Detect Changed Directories and Trigger Notifications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_dirs: ${{ steps.list_dirs.outputs.changed_dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          # Ensure you have the full history for accurate diffs
          git fetch --prune --unshallow

      - name: List changed directories in /configs
        id: list_dirs
        run: |
          # Get the list of changed files between the last commit and the one before it
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          
          # Filter for files within the /configs directory
          CHANGED_CONFIGS_FILES=$(echo "$CHANGED_FILES" | grep '^configs/' | awk -F/ '{print $2}' | sort -u)

          echo "Changed directories within /configs:"
          echo "$CHANGED_CONFIGS_FILES"

          # Set output for use in the next job
          echo "::set-output name=changed_dirs::$(echo "$CHANGED_CONFIGS_FILES")"

  trigger-notification-hub:
    needs: detect-changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger notifications for changed directories
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the list of changed directories from the previous job
          CHANGED_DIRS="${{ needs.detect-changes.outputs.changed_dirs }}"
          
          # Iterate over each directory and trigger the notification hub
          for DIR in $CHANGED_DIRS; do
            echo "Triggering notification for directory: $DIR"
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token $GITHUB_TOKEN" \
              https://api.github.com/repos/golang-devops-hungtnv/project-$DIR/dispatches \
              -d "{\"event_type\":\"directory-changed\", \"client_payload\": {\"directory\": \"$DIR\"}}"
          done
